# Generated by Django 3.2 on 2021-04-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('localtime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
